---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: cluster-02
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: anz-next-demo-23
spec:
  enableAutopilot: true
  location: us-east1
  releaseChannel:
    channel: RAPID
  workloadIdentityConfig:
    workloadPool: anz-next-demo-23.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: cluster-02
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: anz-next-demo-23
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one. To use it, replace ${PROJECT_ID?} with your project ID.
    issuer: https://container.googleapis.com/v1/projects/anz-next-demo-23/locations/us-east1/clusters/cluster-02
  endpoint:
    gkeCluster:
      resourceRef:
        name: cluster-02
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cluster-02
  namespace: flux-system
spec:
  summary: "cluster-02"
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: 'cluster-02'
    namespace: flux-system
  providerRef:
    name: flux-system-dispatch
  eventMetadata:
    project: "anz-next-demo-23"
    cluster: "cluster-02"
    location: "us-east1"
