swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "team-bravo.endpoints.gitops-clusters.cloud.goog"
x-google-endpoints:
- name: "team-bravo.endpoints.gitops-clusters.cloud.goog"
  target: ""
