---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: platform-cicd
  name: team-alpha-reconciler
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:team-alpha-tenant:reconciler
- kind: ServiceAccount
  name: team-alpha
  namespace: team-alpha-tenant
