---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tenant-alpha-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/xunholy/anz-next-demo-23.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-alpha
  namespace: team-alpha-tenant
spec:
  # serviceAccountName: team-alpha
  interval: 5m0s
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: tenant-alpha-repo
    namespace: flux-system
  prune: true
  wait: false
  path: ./apps/overlays/prod/alpha
