---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tenant-alpha-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/xunholy/next-demo-01.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-alpha
  namespace: team-alpha-tenant
spec:
  serviceAccountName: team-alpha
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: tenant-alpha-repo
    namespace: flux-system
  prune: true
  wait: false
  path: ./apps/overlays/cluster-01
