apiVersion: v1
data:
    token: ENC[AES256_GCM,data:Z72BkwiTlDVMvYiKwQAleRxODSH8fdeQ1AAtPIEIbnonE92/zCgraF0GKLmygyscTrRpZHFlGFc=,iv:csG0A+l7bvrIExkdiZqaOfFtI/xmRzkuMiUMpUia6aw=,tag:dIYIZeAL6QAHF27ji23Eew==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-token
    namespace: flux-system
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/anz-next-demo-23/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-08-17T08:40:24Z"
          enc: CiQAj+yNoTkDZcX28vVbjeiwF5gYfgukBYweZc2EojvF3BcXG2MSSQCMFrFyGutRHXCXHWsxT2rgLpeh1eMnNzbZnlSVsFjdzrZ538pytERoR+ptxkuNLni73AnfiV+XoJwxzRqg7Ho1yLkU5MhCmL4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-17T08:40:25Z"
    mac: ENC[AES256_GCM,data:60M/psd7WF74d1b8OSJXpdjd/xhKJuTKW+50C6mlZTzTdRCrjLcCLa4ROuHN4kFIzbxyk7dVxm9XkLCv23K3qk+QVS0eNtiYQNfqAqKGWeCsMp6u58YmwFqHKAg83KgDiJHYJn+qYXRJkvZGyLrq+dnoGuHbEno0i8JTvTvDsyg=,iv:F/rSrpxcFgDAlQZ8stMIqGbdlO2FfRZIhfSIcx8w4xw=,tag:azCtACzuLq+8Qqmzdy9ctw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
